os: osx
osx_image: xcode8

language: cpp

# sudo: required

# dist: trusty

#install:
#- sudo apt-get install libstdc++6 gcc-multilib g++-multilib

install:
- brew install scons valgrind

script:
- s/build
- s/test
- xcodebuild clean build test -project swift/sajson.xcodeproj -scheme sajson-macOS
